[package]
name = "rust-lsm"
version = "0.1.0"
authors = ["Dillon George <dillon.thorsteinn@gmail.com>"]

[dependencies]
enum-primitive-derive = "^0.1"
num-traits = "^0.1"
byteorder = "1.2.6"

[dev-dependencies]
tempfile = "3.0"

